gce/urls.py
from django.urls import path
from .views import (HomeView,
ALGSysView, GCSSysView, FFSSysView, CBRNView,
ALGVideoView,CBRNVideoView,GCSVideoView,FFSVideoView)


app_name = 'gce'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('alg/', ALGSysView.as_view(), name='alg'),
    path('gcs/', GCSSysView.as_view(), name='gcs'),
    path('ffs/', FFSSysView.as_view(), name='ffs'),
    path('cbrn/', CBRNView.as_view(), name='cbrn'),

    path('alg/video/', ALGVideoView.as_view(), name='alg_videos'),
    path('cbr/video/', CBRNVideoView.as_view(), name='cbr_videos'),
    path('gcs/video/', GCSVideoView.as_view(), name='gcs_videos'),
    path('ffs/video/', FFSVideoView.as_view(), name='ffs_videos'),

]

ietm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from users.views import (LoginView, LogoutView, LandingView, 
                        AboutView, RsvView, EsvView, RsvFlowView, 
                        EsvFlowView, RsvTransmitterView, RsvGalleryView, RsvSdpView, RsvIffView, RsvCiuView, RsvDisplaysystemView)
from search.views import SearchView

admin.site.site_header = "IETM Admin"
admin.site.site_title = "IETM Admin Portal"
admin.site.index_title = "Welcome to IETM Admin Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingView.as_view(), name='landing'),
    path('rsv/', RsvView.as_view(), name='rsv'),
    path('rsv/transmitter', RsvTransmitterView.as_view(), name='rsv-transmitter'),
    path('rsv/gallery', RsvGalleryView.as_view(), name='rsv-gallery'),
    path('rsv/rsv-flow-diagram/', RsvFlowView.as_view(), name='rsv-flow-diagram'),
    path('rsv/sdp', RsvSdpView.as_view(), name='rsv-sdp'),
    path('rsv/iff', RsvIffView.as_view(), name='rsv-iff'),
    path('rsv/ciu', RsvCiuView.as_view(), name='rsv-ciu'),
    path('rsv/displaysystem', RsvDisplaysystemView.as_view(), name='rsv-displaysystem'),
    path('esv/', EsvView.as_view(), name='esv'),
    path('esv-flow-diagram/', EsvFlowView.as_view(), name='esv-flow-diagram'),
    path('about/', AboutView.as_view(), name='about'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('auto/', include('auto.urls', namespace="auto")),
    path('elec/', include('elec.urls', namespace="elec")),
    path('gce/', include('gce.urls', namespace="gce")),
    path('ietm/', include('users.urls', namespace="users")),
    # api urls
    path('api/', include('users.api.urls', namespace="api")),
    path('search/', SearchView.as_view(), name='search'),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/api/urls.py
from django.urls import path
from .views import (AxiosFileQuesryset,AxiosVideoQuesryset)


app_name = 'api'
urlpatterns = [
    path('files/', AxiosFileQuesryset.as_view(), name='files'),
    path('videos/', AxiosVideoQuesryset.as_view(), name='videos'),
]

users/urls.py
from django.urls import path

from .views import (HomeView,
AutoSchemView,GceSchemView,ElecSchemView,SchematicsView,
TechnicalLiteratureView,PrecisView,
EMERsView,SMTView,
CBTPPTView,CBTGCEView,CBTGCEiView,CBTAutoView,CBTMainView,PPTMainView,
PPTGCEView,PPTElecView,PPTAutoView,GCELessonsView,
DefectView,
MiscView,MiscFilesView, MiscVideosView,
SearchListView)


app_name = 'users'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('schematics/', SchematicsView.as_view(), name='schem'),
    path('schematics/auto/', AutoSchemView.as_view(), name='sc_auto'),
    path('schematics/gce/', GceSchemView.as_view(), name='sc_gce'),
    path('schematics/elec/', ElecSchemView.as_view(), name='sc_elec'),

    path('tech_lit/', TechnicalLiteratureView.as_view(), name='technical_literature'),
    path('tech_lit/precis/', PrecisView.as_view(), name='precis'),
    
    path('emers/', EMERsView.as_view(), name='emer'),
    path('emers/smt/', SMTView.as_view(), name='smt'),

    path('cbt/', CBTPPTView.as_view(), name='cbt'),
    path('cbts/all', CBTMainView.as_view(), name='cbt_main'),
    path('ppts/all', PPTMainView.as_view(), name='ppt_main'),
    path('cbt/gce/', CBTGCEView.as_view(), name='cbt_gce'),
    path('cbt/gce-electronics/', CBTGCEiView.as_view(), name='cbt_gce_elec'),
    path('cbt/auto/', CBTAutoView.as_view(), name='cbt_auto'),
    path('ppt/auto/', PPTAutoView.as_view(), name='ppt_auto'),
    path('ppt/elec/', PPTElecView.as_view(), name='ppt_elec'),
    path('ppt/gce/', PPTGCEView.as_view(), name='ppt_gce'),
    path('ppt/gce/lessons/', GCELessonsView.as_view(), name='ppt_gce_lessons'),

    path('defects/', DefectView.as_view(), name='defect_report'),

    path('misc/', MiscView.as_view(), name='misc'),
    path('misc/files', MiscFilesView.as_view(), name='misc_files'),
    path('misc/videos', MiscVideosView.as_view(), name='misc_videos'),

    path('results/', SearchListView.as_view(), name='results')
]

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import (authenticate, login, logout, get_user_model)


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self,*args,**kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('This user does not exist or Incorrect Password.')
            if not user.check_password(password):
                raise forms.ValidationError('Incorrect Password')
            if not user.is_active:
                raise forms.ValidationError('User is no longer active.')
        return super(LoginForm, self).clean(*args, **kwargs)



class SearchForm(forms.Form):
    query = forms.CharField(max_length=200)

users/api/views.py
from rest_framework.generics import ListAPIView
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import File, Video
from .serializers import (FileSerializer, VideoSerializer)

class AxiosFileQuesryset(LoginRequiredMixin, ListAPIView):
    queryset = File.objects.all()
    serializer_class = FileSerializer
class AxiosVideoQuesryset(LoginRequiredMixin, ListAPIView):
    queryset = Video.objects.all()
    serializer_class = VideoSerializer

users/views.py
from django.views.generic.edit import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import (authenticate, login, 
logout, get_user_model)
from users.forms import (LoginForm)
from users.models import File, Video, FileObject
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import update_session_auth_hash
from django.views.generic import ListView, DeleteView
from django.contrib.auth.models import User
from django_filters.views import FilterView
from django.db.models import Q
import os
from pathlib import Path
from django.conf import settings
# Create your views here.


#! User Authencation Views

class LoginView(View):


    def get(self,request,*args,**kwargs):
        if request.user.is_authenticated:
            return redirect('users:home')
        else:
            form = LoginForm()
            return render(request, 'users/users_login.html', {'form': form})

    def post(self,request,*args,**kwargs):
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(username=username, password=password)
                login(request, user)
                return redirect('users:home')
        else:
            form = LoginForm()
        return render(request, 'users/users_login.html', {'form': form})

class LogoutView(LoginRequiredMixin,View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return render(request, 'users/users_login.html')

class LandingView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('users:home')
        else:
            return render(request, 'users/users_login.html')

#! Common Views

class HomeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/users_home.html')

class AboutView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/users_about.html')

class RsvView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/rsv.html')

class RsvTransmitterView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/rsv-transmitter.html')

class RsvSdpView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/rsv-sdp.html')

class RsvCiuView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/rsv-ciu.html')

class RsvDisplaysystemView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/rsv-displaysystem.html')


class RsvIffView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/rsv-iff.html')

class RsvGalleryView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/rsv-gallery.html')


class RsvFlowView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/rsv-flow-diagram.html')

class EsvView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/esv.html')

class EsvFlowView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/esv-flow-diagram.html')


# ! SCHEMATIC VIEW
class SchematicsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/schematics/main.html')
class AutoSchemView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        schem_auto = File.objects.filter(content_type='SCHEMATIC DIAGRAM')
        return render(request, 'users/schematics/auto.html', {'schem_auto':schem_auto})
class GceSchemView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        schem_gce = File.objects.filter(content_type='SCHEMATIC DIAGRAM - GCE')
        return render(request, 'users/schematics/gce.html', {'schem_gce':schem_gce})
class ElecSchemView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        schem_elec = File.objects.filter(content_type='SCHEMATIC DIAGRAM - ELEC')
        return render(request, 'users/schematics/elec.html', {'schem_elec':schem_elec})

# ! TECHNICAL LITERATURE 

class TechnicalLiteratureView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        tl = File.objects.filter(content_type='TECHNICAL LITERATURE')
        return render(request, 'users/tech_lit/main.html', {'tl':tl})
class PrecisView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/tech_lit/precis.html')


# ! EMERs VIEW

class EMERsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        emer = File.objects.filter(content_type='EMER')
        return render(request, 'users/emers/main.html', {'emer':emer})
class SMTView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/emers/smt.html')

# ! CBTS/PPTS

class CBTPPTView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/cbt_ppt/main.html')
class CBTMainView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/cbt_ppt/cbt_main.html')
class PPTMainView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        ppt = File.objects.filter(content_type='PPT')
        return render(request, 'users/cbt_ppt/ppt_main.html', {'ppt':ppt})

# CBTs
class CBTGCEView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        gce_path = os.path.join(settings.BASE_DIR,Path('static/CBT/GCE/gec2/Gce_start.exe'))
        os.system(gce_path)
        return render(request, 'users/cbt_ppt/cbt_main.html')   
    def post(self, request, *args, **kwargs):
        gce_path = os.path.join(settings.BASE_DIR,'static/CBT/GCE/gec2/Gce_start.exe')
        os.system(gce_path)
        return render(request, 'users/cbt_ppt/cbt_main.html')
class CBTGCEiView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        gce_path = os.path.join(settings.BASE_DIR,Path('static/CBT/GCE/gec1/ELECTRONICS.exe'))
        os.system(gce_path)
        return render(request, 'users/cbt_ppt/cbt_main.html')   
    def post(self, request, *args, **kwargs):
        gce_path = os.path.join(settings.BASE_DIR,'static/CBT/GCE/gec1/ELECTRONICS.exe')
        os.system(gce_path)
        return render(request, 'users/cbt_ppt/cbt_main.html')
class CBTAutoView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        gce_path = os.path.join(settings.BASE_DIR,Path('static/CBT/Automotive/Auto/MCEME01_2.exe'))
        os.system(gce_path)
        return render(request, 'users/cbt_ppt/cbt_main.html')   
    def post(self, request, *args, **kwargs):
        gce_path = os.path.join(settings.BASE_DIR,'static/CBT/Automotive/Auto/MCEME01_2.exe')
        os.system(gce_path)
        return render(request, 'users/cbt_ppt/cbt_main.html')

# PPTs
class PPTGCEView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        ppt_gce = File.objects.filter(content_type='PPT - GCE')
        return render(request, 'users/cbt_ppt/ppt_gce.html', {'ppt_gce':ppt_gce})
class PPTAutoView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        ppt_auto = File.objects.filter(content_type='PPT - AUTO')
        return render(request, 'users/cbt_ppt/ppt_auto.html', {'ppt_auto':ppt_auto})
class PPTElecView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        ppt_elec = File.objects.filter(content_type='PPT - ELEC')
        return render(request, 'users/cbt_ppt/ppt_elec.html', {'ppt_elec':ppt_elec})


class GCELessonsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/cbt_ppt/ppt_gce_lessons.html')

# ! DEFECT REPORT

class DefectView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        defect_reports = File.objects.filter(content_type='DEFECT REPORT')
        return render(request, 'users/defect_reports.html', {'defect_reports':defect_reports})
# ! MISC VIEW

class MiscView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'users/misc.html')
class MiscFilesView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        misc = File.objects.filter(content_type='MISC')
        return render(request, 'users/misc_files.html', {'misc':misc})
class MiscVideosView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        misc = Video.objects.filter(video_type='MISC')
        return render(request, 'users/misc_videos.html', {'misc':misc})


# ! Search Views

class SearchListView(LoginRequiredMixin, ListView):
    template_name = 'users/search.html'
    def get_queryset(self):
        query = str(self.request.GET.get('q'))
        if query is not None:
            queryset = {
            'files': File.objects.filter(name__icontains=query),

users/templates/users/cbt_ppt/cbt_main.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  CBTs
{% endblock %}

{% block breadcrumb %}
<div class="menu__crumbs d-flex w-100">
  <div class="container p-0 d-flex justify-content-between">
    <div>
      <a class="btn" href="{% url 'users:home' %}" role="button">Home</a><span>></span>
      <a class="btn" href="#" role="button">CBTs</a>
    </div>
  </div>
</div>
{% endblock breadcrumb %}

{% block content %}
  <div class="container center" style="margin-top: 2rem;">
      <div class="row d-flex justify-content-center">
        <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
          <form method="post">
              {% csrf_token %}
            <a href="{% url 'users:cbt_auto' %}" type="submit">
                <div class="card item-card card-block">
                  <img src="{% static 'img/cbt.jpg' %}" alt="Automotive">
                    <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Automotive</h3>
                  </div>
            </a>
          </form>
        </div>
        <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
            <form method="post">
                <a href="{% url 'users:cbt_gce' %}" type="submit">
                    <div class="card item-card card-block">
                      <img src="{% static 'img/cbt.jpg' %}" alt="GCE">
                    <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">GCE</h3>
                    </div>
                </a>
            </form>
        </div>
        <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
          <form method="post">
            <a href="{% url 'users:cbt_gce_elec' %}" type="submit">
                <div class="card item-card card-block">
                  <img src="{% static 'img/cbt.jpg' %}" alt="GCE Electronics">
                    <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">GCE Electronics</h3>
                </div>
            </a>
          </form>
        </div>  
      </div>
  </div>
{% endblock content %}

users/templates/users/cbt_ppt/main.html
{% extends 'base.html' %}
{% load static %}
<!-- TODO Add schematics for auto and electrical -->
{% block title %}
    <title>
        CBTs/PPTs
    </title>
{% endblock title %}


{% block content %}
<!--<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'users:home' %}">Home</a></li>
      <li class="breadcrumb-item">CBTs/PPTs</li>
    </ol>
  </nav>
  <div class="container center" style="margin-top: 2rem;">
      <div class="row">
        <div class="col-md-4 col-sm-6 item" style="padding-right: 1rem;">
            <a href="{% url 'users:cbt_main' %}">
              <div class="card item-card card-block">
                <img src="{% static 'img/cbt.jpg' %}" alt="Computer Based Training">
                  <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Computer Based Training</h3>
                </div>
            </a>
          </div>
          <div class="col-md-4 col-sm-6 item" style="padding-right: 1rem;">
            <a href="{% url 'users:ppt_main' %}">
              <div class="card item-card card-block">
                <img src="{% static 'img/ppt.png' %}" alt="PPTs">
                  <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">PPTs</h3>
                </div>
            </a>
          </div>                                  
      </div>
  </div>-->
  <section
      class="d-flex align-items-start contentArea w-100 position-absolute"
    >
      <div
        class="content__inner w-100 h-100 d-flex flex-column position-relative pb-2"
      >
        <div class="container">
          <div class="d-flex pt-5 justify-content-center align-items-center w-100">
            <a class="btn button" href="{% url 'users:cbt_main' %}" role="button">CBTs</a>
            <a class="btn button" href="{% url 'users:ppt_main' %}" role="button">PPTs</a>
          </div>
        </div>
      </div>
    </section>
{% endblock content %}

users/templates/users/cbt_ppt/ppt_auto.html
{% extends 'rebase.html' %}
{% load static %}
{% block title %}
    <title>
        Automotive - PPTs
    </title>
{% endblock title %}

{% block style %}
<style>
    img{
height:150px;
width:100%;
}

.item{
padding-left:5px;
padding-right:5px;
}
.item-card{
transition:0.5s;
cursor:pointer;
}
.item-card-title{  
font-size:15px;
transition:1s;
cursor:pointer;
}
.item-card-title i{  
font-size:15px;
transition:1s;
cursor:pointer;
color:#ffa710
}
.card-title i:hover{
transform: scale(1.25) rotate(100deg); 
color:#18d4ca;

}
.card:hover{
transform: scale(1.05);
box-shadow: 10px 10px 15px rgba(0,0,0,0.3);
}
.card-text{
height:80px;  
}

.card::before, .card::after {
position: absolute;
top: 0;
right: 0;
bottom: 0;
left: 0;
transform: scale3d(0, 0, 1);
transition: transform .3s ease-out 0s;
background: rgba(255, 255, 255, 0.1);
content: '';
pointer-events: none;
}
.card::before {
transform-origin: left top;
}
.card::after {
transform-origin: right bottom;
}
.card:hover::before, .card:hover::after, .card:focus::before, .card:focus::after {
transform: scale3d(1, 1, 1);
}
</style>
{% endblock style %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'users:home' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'users:cbt' %}">CBTs/PPTs</a></li>
      <li class="breadcrumb-item"><a href="{% url 'users:ppt_main' %}">PPTs</a></li>
      <li class="breadcrumb-item">Automotive - PPTs</li>
    </ol>
  </nav>
  <div class="container center" style="margin-top: 2rem;">
    <table class="table table-striped ">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name of the Lesson</th>
            <th scope="col">Download</th>
          </tr>
        </thead>
        <tbody>
          {% for item in ppt_auto %}
          <tr>
            <th>{{item.name|upper}}</th>
            <td><a href="{{item.file.url}}"><i class="fas fa-download"></i></a></td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
  </div>
{% endblock content %}

users/templates/users/cbt_ppt/ppt_elec.html
{% extends 'rebase.html' %}
{% load static %}
{% block title %}
    <title>
        Electrical - PPTs
    </title>
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/all.css' %}">
{% endblock style %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'users:home' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'users:cbt' %}">CBTs/PPTs</a></li>
      <li class="breadcrumb-item"><a href="{% url 'users:ppt_main' %}">PPTs</a></li>
      <li class="breadcrumb-item">Electrical - PPTs</li>
    </ol>
  </nav>
  <div class="container center" style="margin-top: 2rem;">
    <table class="table table-striped ">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name of the Lesson</th>
            <th scope="col">Download</th>
          </tr>
        </thead>
        <tbody>
          {% for item in ppt_elec %}
          <tr>
            <th>{{item.name|upper}}</th>
            <td><a href="{{item.file.url}}"><i class="fas fa-download"></i></a></td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
  </div>
{% endblock content %}

users/templates/users/cbt_ppt/ppt_gce.html
{% extends 'rebase.html' %}
{% load static %}

{% block title %}
    <title>
        GCE - Lessons
    </title>
{% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/all.css' %}">
{% endblock style %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'users:home' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'users:cbt' %}">CBTs/PPTs</a></li>
      <li class="breadcrumb-item"><a href="{% url 'users:ppt_main' %}">PPTs</a></li>
      <!-- <li class="breadcrumb-item"><a href="{% url 'users:ppt_gce' %}">GCE - PPTs</a></li> -->
      <li class="breadcrumb-item">GCE - PPTs</li>
    </ol>
</nav>
  <div class="container center" style="margin-top: 2rem;">
    <table class="table table-striped ">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name of the Lesson</th>
            <th scope="col">Download</th>
          </tr>
        </thead>
        <tbody>
          {% for item in ppt_gce %}
          <tr>
            <th>{{item.name|upper}}</th>
            <td><a href="{{item.file.url}}"><i class="fas fa-download"></i></a></td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
  </div>
{% endblock content %}

users/templates/users/cbt_ppt/ppt_main.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
PPTs
{% endblock %}

{% block breadcrumb %}
<div class="menu__crumbs d-flex w-100">
  <div class="container p-0 d-flex justify-content-between">
    <div>
      <a class="btn" href="{% url 'users:home' %}" role="button">Home</a><span>></span>
      <a class="btn" href="#" role="button">PPTs</a>
    </div>
  </div>
</div>
{% endblock breadcrumb %}

{% block content %}
<!--<div class="container center" style="margin-top: 2rem;">
      <div class="row">
          <div class="col-md-4 col-sm-6 item" style="padding-right: 1rem;">
            <a href="{% url 'users:ppt_auto' %}">
                <div class="card item-card card-block">
                  <img src="{% static 'img/ppt.png' %}" alt="Automotive System">
                  <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Automotive System</h3>
                </div>
            </a>
          </div>
          <div class="col-md-4 col-sm-6 item" style="padding-right: 1rem;">
            <a href="{% url 'users:ppt_gce' %}">
                <div class="card item-card card-block">
                  <img src="{% static 'img/ppt.png' %}" alt="Gun Control System">
                  <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Gun Control System</h3>
                </div>
            </a>
          </div>
          <div class="col-md-4 col-sm-6 item" style="padding-right: 1rem;">
            <a href="{% url 'users:ppt_elec' %}">
                <div class="card item-card card-block">
                  <img src="{% static 'img/ppt.png' %}" alt="Electrical System">
                  <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Electrical System</h3>
                </div>
            </a>
          </div>                                   
      </div>
  </div>-->
<section class="d-flex align-items-start contentArea w-100 position-absolute">
  <div class="content__inner w-100 h-100 d-flex flex-column position-relative pb-2">
    <div class="container">
      <div class="d-flex pt-5 justify-content-center align-items-center w-100">
        <a href="{% url 'users:ppt_auto' %}" class="btn button" role="button">Automotive System</a>
        <a href="{% url 'users:ppt_gce' %}" class="btn button" role="button">Gun Control System </a>
        <a href="{% url 'users:ppt_elec' %}" class="btn button" role="button">Electrical System</a>
      </div>
    </div>
  </div>
</section>
{% endblock content %}