elec/urls.py
from django.urls import path
from .views import (HomeView,
ChargingAccessoryView, ChargingSysView, LightingSysView, StartingSysView,
ChargingEMERView,
AccessoryVideoView, StartingVideoView, LightingVideoView, ChargingVideoView)


app_name = 'elec'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('charging/', ChargingSysView.as_view(), name='charging'),
    path('lighting/', LightingSysView.as_view(), name='lighting'),
    path('starting/', StartingSysView.as_view(), name='starting'),
    path('accessory/', ChargingAccessoryView.as_view(), name='accessory'),
    path('charging/videos', ChargingVideoView.as_view(), name='c_vid'),
    path('lighting/videos', LightingVideoView.as_view(), name='l_vid'),
    path('starting/videos', StartingVideoView.as_view(), name='s_vid'),
    path('accessory/videos', AccessoryVideoView.as_view(), name='a_vid'),

    path('charging/emers/', ChargingEMERView.as_view(), name='charging_emer'),



]

gce/urls.py
from django.urls import path
from .views import (HomeView,
ALGSysView, GCSSysView, FFSSysView, CBRNView,
ALGVideoView,CBRNVideoView,GCSVideoView,FFSVideoView)


app_name = 'gce'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('alg/', ALGSysView.as_view(), name='alg'),
    path('gcs/', GCSSysView.as_view(), name='gcs'),
    path('ffs/', FFSSysView.as_view(), name='ffs'),
    path('cbrn/', CBRNView.as_view(), name='cbrn'),

    path('alg/video/', ALGVideoView.as_view(), name='alg_videos'),
    path('cbr/video/', CBRNVideoView.as_view(), name='cbr_videos'),
    path('gcs/video/', GCSVideoView.as_view(), name='gcs_videos'),
    path('ffs/video/', FFSVideoView.as_view(), name='ffs_videos'),

]

ietm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from users.views import (LoginView, LogoutView, LandingView, 
                        AboutView, RsvView, EsvView, RsvFlowView, 
                        EsvFlowView, RsvTransmitterView, RsvGalleryView, RsvSdpView, RsvIffView, RsvCiuView, RsvDisplaysystemView)
from search.views import SearchView

admin.site.site_header = "IETM Admin"
admin.site.site_title = "IETM Admin Portal"
admin.site.index_title = "Welcome to IETM Admin Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingView.as_view(), name='landing'),
    path('rsv/', RsvView.as_view(), name='rsv'),
    path('rsv/transmitter', RsvTransmitterView.as_view(), name='rsv-transmitter'),
    path('rsv/gallery', RsvGalleryView.as_view(), name='rsv-gallery'),
    path('rsv/rsv-flow-diagram/', RsvFlowView.as_view(), name='rsv-flow-diagram'),
    path('rsv/sdp', RsvSdpView.as_view(), name='rsv-sdp'),
    path('rsv/iff', RsvIffView.as_view(), name='rsv-iff'),
    path('rsv/ciu', RsvCiuView.as_view(), name='rsv-ciu'),
    path('rsv/displaysystem', RsvDisplaysystemView.as_view(), name='rsv-displaysystem'),
    path('esv/', EsvView.as_view(), name='esv'),
    path('esv-flow-diagram/', EsvFlowView.as_view(), name='esv-flow-diagram'),
    path('about/', AboutView.as_view(), name='about'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('auto/', include('auto.urls', namespace="auto")),
    path('elec/', include('elec.urls', namespace="elec")),
    path('gce/', include('gce.urls', namespace="gce")),
    path('ietm/', include('users.urls', namespace="users")),
    # api urls
    path('api/', include('users.api.urls', namespace="api")),
    path('search/', SearchView.as_view(), name='search'),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elec/models.py
from django.db import models

# Create your models here.

elec/views.py
from django.shortcuts import render
from django.views.generic.edit import View
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import File, Video
from itertools import chain

# Create your views here.


class HomeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'elec/elec_home.html')

# ! SUBSYSTEMS
class ChargingSysView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'elec/charging.html')
class StartingSysView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'elec/starting.html')
class LightingSysView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'elec/lighting.html')
class ChargingAccessoryView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'elec/accessory.html')

# ! DATA VIEWS
# Charging Sys
class ChargingEMERView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        crumb = 'EMER'
        subsystem = 'Charging System'
        link = '{{% url "elec:charging_emer" %}}'
        # datalist = File.objects.filter(subsystem="CHARGING", content_type="EMERS")
        datalist=''
        return render(request, 'elec/data.html', {'crumb':crumb, 'sub':subsystem, 'datalist':datalist})


# ! Video VIEWS
# Charging
class ChargingVideoView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        datalist = Video.objects.filter(video_type="CHARGING")
        return render(request, 'elec/videos/charging.html', {'datalist':datalist})
# lighting
class LightingVideoView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        datalist = Video.objects.filter(video_type="LIGHTING")
        return render(request, 'elec/videos/lighting.html', {'datalist':datalist})
# starting
class StartingVideoView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        datalist = Video.objects.filter(video_type="STARTING")
        return render(request, 'elec/videos/starting.html', {'datalist':datalist})
# accesory
class AccessoryVideoView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        datalist = Video.objects.filter(video_type="ACCESSORY")
        return render(request, 'elec/videos/accessory.html', {'datalist':datalist})

elec/templates/elec/videos/accessory.html
{% extends 'rebase.html' %}
{% load static %}

{% block style %}
<style>
    img{
height:150px;
width:100%;
}

.item{
padding-left:5px;
padding-right:5px;
}
.item-card{
transition:0.5s;
cursor:pointer;
}
.item-card-title{  
font-size:15px;
transition:1s;
cursor:pointer;
}
.item-card-title i{  
font-size:15px;
transition:1s;
cursor:pointer;
color:#ffa710
}
.card-title i:hover{
transform: scale(1.25) rotate(100deg); 
color:#18d4ca;

}
.card:hover{
transform: scale(1.05);
box-shadow: 10px 10px 15px rgba(0,0,0,0.3);
}
.card-text{
height:80px;  
}

.card::before, .card::after {
position: absolute;
top: 0;
right: 0;
bottom: 0;
left: 0;
transform: scale3d(0, 0, 1);
transition: transform .3s ease-out 0s;
background: rgba(255, 255, 255, 0.1);
content: '';
pointer-events: none;
}
.card::before {
transform-origin: left top;
}
.card::after {
transform-origin: right bottom;
}
.card:hover::before, .card:hover::after, .card:focus::before, .card:focus::after {
transform: scale3d(1, 1, 1);
}
</style>
{% endblock style %}

{% block title %}
    <title>
        Accessory Ckt Videos
    </title>
{% endblock title %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'users:home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'elec:home' %}">Electrical Sys</a></li>
    <li class="breadcrumb-item"><a href="{% url 'elec:accessory' %}">Accessory Ckt</a></li>
    <li class="breadcrumb-item">Videos</li>
  </ol>
</nav>
<div class="container center" style="margin-top: 2rem;">
  <div class="row">
    {% for item in datalist %}
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem; margin-top: 1rem;">
        <a href="{{item.file.url}}" target="_blank">
          <div class="card item-card card-block">
            <img src="{% static 'img/video.png' %}" alt="{{item.name}}">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">{{item.name|title}}</h3>
            </div>
        </a>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

elec/templates/elec/videos/charging.html
{% extends 'rebase.html' %}
{% load static %}

{% block style %}
<style>
    img{
height:150px;
width:100%;
}

.item{
padding-left:5px;
padding-right:5px;
}
.item-card{
transition:0.5s;
cursor:pointer;
}
.item-card-title{  
font-size:15px;
transition:1s;
cursor:pointer;
}
.item-card-title i{  
font-size:15px;
transition:1s;
cursor:pointer;
color:#ffa710
}
.card-title i:hover{
transform: scale(1.25) rotate(100deg); 
color:#18d4ca;

}
.card:hover{
transform: scale(1.05);
box-shadow: 10px 10px 15px rgba(0,0,0,0.3);
}
.card-text{
height:80px;  
}

.card::before, .card::after {
position: absolute;
top: 0;
right: 0;
bottom: 0;
left: 0;
transform: scale3d(0, 0, 1);
transition: transform .3s ease-out 0s;
background: rgba(255, 255, 255, 0.1);
content: '';
pointer-events: none;
}
.card::before {
transform-origin: left top;
}
.card::after {
transform-origin: right bottom;
}
.card:hover::before, .card:hover::after, .card:focus::before, .card:focus::after {
transform: scale3d(1, 1, 1);
}
</style>
{% endblock style %}

{% block title %}
    <title>
        Charging Ckt Videos
    </title>
{% endblock title %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'users:home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'elec:home' %}">Electrical Sys</a></li>
    <li class="breadcrumb-item"><a href="{% url 'elec:charging' %}">Charging Ckt</a></li>
    <li class="breadcrumb-item">Videos</li>
  </ol>
</nav>
<div class="container center" style="margin-top: 2rem;">
  <div class="row">
    {% for item in datalist %}
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem; margin-top: 1rem;">
        <a href="{{item.file.url}}" target="_blank">
          <div class="card item-card card-block">
            <img src="{% static 'img/video.png' %}" alt="{{item.name}}">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">{{item.name|title}}</h3>
            </div>
        </a>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

elec/templates/elec/videos/lighting.html
{% extends 'rebase.html' %}
{% load static %}

{% block style %}
<style>
    img{
height:150px;
width:100%;
}

.item{
padding-left:5px;
padding-right:5px;
}
.item-card{
transition:0.5s;
cursor:pointer;
}
.item-card-title{  
font-size:15px;
transition:1s;
cursor:pointer;
}
.item-card-title i{  
font-size:15px;
transition:1s;
cursor:pointer;
color:#ffa710
}
.card-title i:hover{
transform: scale(1.25) rotate(100deg); 
color:#18d4ca;

}
.card:hover{
transform: scale(1.05);
box-shadow: 10px 10px 15px rgba(0,0,0,0.3);
}
.card-text{
height:80px;  
}

.card::before, .card::after {
position: absolute;
top: 0;
right: 0;
bottom: 0;
left: 0;
transform: scale3d(0, 0, 1);
transition: transform .3s ease-out 0s;
background: rgba(255, 255, 255, 0.1);
content: '';
pointer-events: none;
}
.card::before {
transform-origin: left top;
}
.card::after {
transform-origin: right bottom;
}
.card:hover::before, .card:hover::after, .card:focus::before, .card:focus::after {
transform: scale3d(1, 1, 1);
}
</style>
{% endblock style %}

{% block title %}
    <title>
        Lighting Videos
    </title>
{% endblock title %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'users:home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'elec:home' %}">Electrical Sys</a></li>
    <li class="breadcrumb-item"><a href="{% url 'elec:lighting' %}">Lighting</a></li>
    <li class="breadcrumb-item">Videos</li>
  </ol>
</nav>
<div class="container center" style="margin-top: 2rem;">
  <div class="row">
    {% for item in datalist %}
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem; margin-top: 1rem;">
        <a href="{{item.file.url}}" target="_blank">
          <div class="card item-card card-block">
            <img src="{% static 'img/video.png' %}" alt="{{item.name}}">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">{{item.name|title}}</h3>
            </div>
        </a>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

elec/templates/elec/videos/starting.html
{% extends 'rebase.html' %}
{% load static %}

{% block style %}
<style>
    img{
height:150px;
width:100%;
}

.item{
padding-left:5px;
padding-right:5px;
}
.item-card{
transition:0.5s;
cursor:pointer;
}
.item-card-title{  
font-size:15px;
transition:1s;
cursor:pointer;
}
.item-card-title i{  
font-size:15px;
transition:1s;
cursor:pointer;
color:#ffa710
}
.card-title i:hover{
transform: scale(1.25) rotate(100deg); 
color:#18d4ca;

}
.card:hover{
transform: scale(1.05);
box-shadow: 10px 10px 15px rgba(0,0,0,0.3);
}
.card-text{
height:80px;  
}

.card::before, .card::after {
position: absolute;
top: 0;
right: 0;
bottom: 0;
left: 0;
transform: scale3d(0, 0, 1);
transition: transform .3s ease-out 0s;
background: rgba(255, 255, 255, 0.1);
content: '';
pointer-events: none;
}
.card::before {
transform-origin: left top;
}
.card::after {
transform-origin: right bottom;
}
.card:hover::before, .card:hover::after, .card:focus::before, .card:focus::after {
transform: scale3d(1, 1, 1);
}
</style>
{% endblock style %}

{% block title %}
    <title>
        Starting Ckt Videos
    </title>
{% endblock title %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'users:home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'elec:home' %}">Electrical Sys</a></li>
    <li class="breadcrumb-item"><a href="{% url 'elec:starting' %}">Starting Ckt</a></li>
    <li class="breadcrumb-item">Videos</li>
  </ol>
</nav>
<div class="container center" style="margin-top: 2rem;">
  <div class="row">
    {% for item in datalist %}
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem; margin-top: 1rem;">
        <a href="{{item.file.url}}" target="_blank">
          <div class="card item-card card-block">
            <img src="{% static 'img/video.png' %}" alt="{{item.name}}">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">{{item.name|title}}</h3>
            </div>
        </a>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}