gce/urls.py
from django.urls import path
from .views import (HomeView,
ALGSysView, GCSSysView, FFSSysView, CBRNView,
ALGVideoView,CBRNVideoView,GCSVideoView,FFSVideoView)


app_name = 'gce'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('alg/', ALGSysView.as_view(), name='alg'),
    path('gcs/', GCSSysView.as_view(), name='gcs'),
    path('ffs/', FFSSysView.as_view(), name='ffs'),
    path('cbrn/', CBRNView.as_view(), name='cbrn'),

    path('alg/video/', ALGVideoView.as_view(), name='alg_videos'),
    path('cbr/video/', CBRNVideoView.as_view(), name='cbr_videos'),
    path('gcs/video/', GCSVideoView.as_view(), name='gcs_videos'),
    path('ffs/video/', FFSVideoView.as_view(), name='ffs_videos'),

]

ietm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from users.views import (LoginView, LogoutView, LandingView, 
                        AboutView, RsvView, EsvView, RsvFlowView, 
                        EsvFlowView, RsvTransmitterView, RsvGalleryView, RsvSdpView, RsvIffView, RsvCiuView, RsvDisplaysystemView)
from search.views import SearchView

admin.site.site_header = "IETM Admin"
admin.site.site_title = "IETM Admin Portal"
admin.site.index_title = "Welcome to IETM Admin Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingView.as_view(), name='landing'),
    path('rsv/', RsvView.as_view(), name='rsv'),
    path('rsv/transmitter', RsvTransmitterView.as_view(), name='rsv-transmitter'),
    path('rsv/gallery', RsvGalleryView.as_view(), name='rsv-gallery'),
    path('rsv/rsv-flow-diagram/', RsvFlowView.as_view(), name='rsv-flow-diagram'),
    path('rsv/sdp', RsvSdpView.as_view(), name='rsv-sdp'),
    path('rsv/iff', RsvIffView.as_view(), name='rsv-iff'),
    path('rsv/ciu', RsvCiuView.as_view(), name='rsv-ciu'),
    path('rsv/displaysystem', RsvDisplaysystemView.as_view(), name='rsv-displaysystem'),
    path('esv/', EsvView.as_view(), name='esv'),
    path('esv-flow-diagram/', EsvFlowView.as_view(), name='esv-flow-diagram'),
    path('about/', AboutView.as_view(), name='about'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('auto/', include('auto.urls', namespace="auto")),
    path('elec/', include('elec.urls', namespace="elec")),
    path('gce/', include('gce.urls', namespace="gce")),
    path('ietm/', include('users.urls', namespace="users")),
    # api urls
    path('api/', include('users.api.urls', namespace="api")),
    path('search/', SearchView.as_view(), name='search'),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gce/views.py
from django.shortcuts import render
from django.views.generic.edit import View
from django.contrib.auth.mixins import LoginRequiredMixin
from users.models import File, Video
from itertools import chain

# Create your views here.


class HomeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'gce/gce_home.html')

# ! SUBSYSTEMS
class GCSSysView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'gce/gcs.html')
class ALGSysView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'gce/alg.html')
class FFSSysView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'gce/ffs.html')
class CBRNView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, 'gce/cbrn.html')

# ! Video VIEWS
# ALG
class ALGVideoView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        datalist = Video.objects.filter(video_type="ALG")
        return render(request, 'gce/videos/alg.html', {'datalist':datalist})
# CBRN
class CBRNVideoView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        datalist = Video.objects.filter(video_type="CBRN")
        return render(request, 'gce/videos/cbrn.html', {'datalist':datalist})
# FFS
class FFSVideoView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        datalist = Video.objects.filter(video_type="FFS")
        return render(request, 'gce/videos/ffs.html', {'datalist':datalist})
# GCS
class GCSVideoView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        datalist = Video.objects.filter(video_type="GCE")
        return render(request, 'gce/videos/gcs.html', {'datalist':datalist})

gce/templates/gce/alg.html
{% extends 'rebase.html' %}
{% load static %}

{% block style %}
<style>
    img{
height:150px;
width:100%;
}

.item{
padding-left:5px;
padding-right:5px;
}
.item-card{
transition:0.5s;
cursor:pointer;
}
.item-card-title{  
font-size:15px;
transition:1s;
cursor:pointer;
}
.item-card-title i{  
font-size:15px;
transition:1s;
cursor:pointer;
color:#ffa710
}
.card-title i:hover{
transform: scale(1.25) rotate(100deg); 
color:#18d4ca;

}
.card:hover{
transform: scale(1.05);
box-shadow: 10px 10px 15px rgba(0,0,0,0.3);
}
.card-text{
height:80px;  
}

.card::before, .card::after {
position: absolute;
top: 0;
right: 0;
bottom: 0;
left: 0;
transform: scale3d(0, 0, 1);
transition: transform .3s ease-out 0s;
background: rgba(255, 255, 255, 0.1);
content: '';
pointer-events: none;
}
.card::before {
transform-origin: left top;
}
.card::after {
transform-origin: right bottom;
}
.card:hover::before, .card:hover::after, .card:focus::before, .card:focus::after {
transform: scale3d(1, 1, 1);
}
</style>
{% endblock style %}

{% block title %}
    <title>
        Autoloading Gear
    </title>
{% endblock title %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'users:home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'gce:home' %}">GCE</a></li>
    <li class="breadcrumb-item">ALG</li>
  </ol>
</nav>
<div class="container center" style="margin-top: 2rem;">
    <div class="row">
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
        <a href="{% static 'FILES/GCE/Technical Manual T-72.pdf' %}#page=73" target="_blank">
          <div class="card item-card card-block">
            <img src="{% static 'img/manual.png' %}" alt="Technical Manual">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Technical Manual</h3>
            </div>
        </a>
      </div>
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
        <a href="{% static 'FILES/GCE/OS-all.pdf' %}#page=424" target="_blank">
          <div class="card item-card card-block">
            <img src="{% static 'img/doc.jpg' %}" alt="Overhaul Scale">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Overhaul Scale</h3>
            </div>
        </a>
      </div>    
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
        <a href="{% static 'FILES/GCE/ALG_T-72.pdf' %}" target="_blank">
          <div class="card item-card card-block">
            <img src="{% static 'img/precis.png' %}" alt="Precis">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Precis</h3>
            </div>
        </a>
      </div>    
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
        <a href="{% static 'FILES/GCE/SCHEMATIC/ALG.pdf' %}" target="_blank">
          <div class="card item-card card-block">
            <img src="{% static 'img/circuit.png' %}" alt="Circuit/Schematic Diag">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Circuit/Schematic Diag</h3>
            </div>
        </a>
      </div>    
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem; margin-top: 1rem;">
        <a href="{% url 'gce:alg_videos' %}">
          <div class="card item-card card-block">
            <img src="{% static 'img/vid.png' %}" alt="Videos">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Videos</h3>
            </div>
        </a>
      </div>         
    </div>
</div>
{% endblock content %}

gce/templates/gce/cbrn.html
{% extends 'rebase.html' %}
{% load static %}

{% block style %}
<style>
    img{
height:150px;
width:100%;
}

.item{
padding-left:5px;
padding-right:5px;
}
.item-card{
transition:0.5s;
cursor:pointer;
}
.item-card-title{  
font-size:15px;
transition:1s;
cursor:pointer;
}
.item-card-title i{  
font-size:15px;
transition:1s;
cursor:pointer;
color:#ffa710
}
.card-title i:hover{
transform: scale(1.25) rotate(100deg); 
color:#18d4ca;

}
.card:hover{
transform: scale(1.05);
box-shadow: 10px 10px 15px rgba(0,0,0,0.3);
}
.card-text{
height:80px;  
}

.card::before, .card::after {
position: absolute;
top: 0;
right: 0;
bottom: 0;
left: 0;
transform: scale3d(0, 0, 1);
transition: transform .3s ease-out 0s;
background: rgba(255, 255, 255, 0.1);
content: '';
pointer-events: none;
}
.card::before {
transform-origin: left top;
}
.card::after {
transform-origin: right bottom;
}
.card:hover::before, .card:hover::after, .card:focus::before, .card:focus::after {
transform: scale3d(1, 1, 1);
}
</style>
{% endblock style %}

{% block title %}
    <title>
        CBR
    </title>
{% endblock title %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'users:home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'gce:home' %}">GCE</a></li>
    <li class="breadcrumb-item">CBR</li>
  </ol>
</nav>
<div class="container center" style="margin-top: 2rem;">
    <div class="row">
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
        <a href="{% static 'FILES/GCE/Technical Manual T-72.pdf' %}#page=328" target="_blank">
          <div class="card item-card card-block">
            <img src="{% static 'img/manual.png' %}" alt="Technical Manual">
            <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Technical Manual</h3>
          </div>
        </a>
      </div>
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
        <a href="{% static 'FILES/GCE/CBR.pdf' %}" target="_blank">
          <div class="card item-card card-block">
            <img src="{% static 'img/precis.png' %}" alt="Precis">
            <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Precis</h3>
          </div>
        </a>
      </div>
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
        <a href="{% static 'FILES/GCE/SCHEMATIC/CBR_PROTECTION_SYS.pdf' %}" target="_blank">
          <div class="card item-card card-block">
            <img src="{% static 'img/circuit.png' %}" alt="Circuit/Schematic Diag">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Circuit/Schematic Diag</h3>
            </div>
        </a>
      </div>          
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
        <a href="{% url 'gce:cbr_videos' %}">
          <div class="card item-card card-block">
            <img src="{% static 'img/vid.png' %}" alt="Videos">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Videos</h3>
            </div>
        </a>
      </div>      
    </div>
</div>
{% endblock content %}

gce/templates/gce/ffs.html
{% extends 'rebase.html' %}
{% load static %}

{% block style %}
<style>
    img{
height:150px;
width:100%;
}

.item{
padding-left:5px;
padding-right:5px;
}
.item-card{
transition:0.5s;
cursor:pointer;
}
.item-card-title{  
font-size:15px;
transition:1s;
cursor:pointer;
}
.item-card-title i{  
font-size:15px;
transition:1s;
cursor:pointer;
color:#ffa710
}
.card-title i:hover{
transform: scale(1.25) rotate(100deg); 
color:#18d4ca;

}
.card:hover{
transform: scale(1.05);
box-shadow: 10px 10px 15px rgba(0,0,0,0.3);
}
.card-text{
height:80px;  
}

.card::before, .card::after {
position: absolute;
top: 0;
right: 0;
bottom: 0;
left: 0;
transform: scale3d(0, 0, 1);
transition: transform .3s ease-out 0s;
background: rgba(255, 255, 255, 0.1);
content: '';
pointer-events: none;
}
.card::before {
transform-origin: left top;
}
.card::after {
transform-origin: right bottom;
}
.card:hover::before, .card:hover::after, .card:focus::before, .card:focus::after {
transform: scale3d(1, 1, 1);
}
</style>
{% endblock style %}

{% block title %}
    <title>
        Fire Fighting
    </title>
{% endblock title %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'users:home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'gce:home' %}">GCE</a></li>
    <li class="breadcrumb-item">Fire Fighting System</li>
  </ol>
</nav>
<div class="container center" style="margin-top: 2rem;">
  <div class="row">
        
    <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
      <a href="{% static 'FILES/GCE/Technical Manual T-72.pdf' %}#page=322" target="_blank">
        <div class="card item-card card-block">
          <img src="{% static 'img/manual.png' %}" alt="Technical Manual">
            <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Technical Manual</h3>
          </div>
      </a>
    </div>   
    <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
      <a href="{% static 'FILES/GCE/Fire-Fighting System.pdf' %}" target="_blank">
        <div class="card item-card card-block">
          <img src="{% static 'img/precis.png' %}" alt="Preci">
            <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Preci</h3>
          </div>
      </a>
    </div>    
    <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
      <a href="{% url 'gce:ffs_videos' %}">
        <div class="card item-card card-block">
          <img src="{% static 'img/vid.png' %}" alt="Videos">
            <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Videos</h3>
          </div>
      </a>
    </div>         
  </div>
</div>
{% endblock content %}

gce/templates/gce/gce_home.html
{% extends 'rebase.html' %}
{% load static %}

{% block style %}
<style>
    img{
height:150px;
width:100%;
}

.item{
padding-left:5px;
padding-right:5px;
}
.item-card{
transition:0.5s;
cursor:pointer;
}
.item-card-title{  
font-size:15px;
transition:1s;
cursor:pointer;
}
.item-card-title i{  
font-size:15px;
transition:1s;
cursor:pointer;
color:#ffa710
}
.card-title i:hover{
transform: scale(1.25) rotate(100deg); 
color:#18d4ca;

}
.card:hover{
transform: scale(1.05);
box-shadow: 10px 10px 15px rgba(0,0,0,0.3);
}
.card-text{
height:80px;  
}

.card::before, .card::after {
position: absolute;
top: 0;
right: 0;
bottom: 0;
left: 0;
transform: scale3d(0, 0, 1);
transition: transform .3s ease-out 0s;
background: rgba(255, 255, 255, 0.1);
content: '';
pointer-events: none;
}
.card::before {
transform-origin: left top;
}
.card::after {
transform-origin: right bottom;
}
.card:hover::before, .card:hover::after, .card:focus::before, .card:focus::after {
transform: scale3d(1, 1, 1);
}
</style>
{% endblock style %}

{% block title %}
    <title>
        Gun Control System
    </title>
{% endblock title %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'users:home' %}">Home</a></li>
    <li class="breadcrumb-item">GCE</li>
  </ol>
</nav>
<div class="container center" style="margin-top: 2rem;">
    <div class="row">
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
        <a href="{% url 'gce:alg' %}">
          <div class="card item-card card-block">
            <img src="{% static 'img/alg.jpg' %}" alt="ALG">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">ALG</h3>
            </div>
        </a>
      </div>
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
        <a href="{% url 'gce:gcs' %}">
          <div class="card item-card card-block">
            <img src="{% static 'img/fcs.jpg' %}" alt="GCE">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">GCE</h3>
            </div>
        </a>
      </div>
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
        <a href="{% url 'gce:cbrn' %}">
          <div class="card item-card card-block">
            <img src="{% static 'img/cbrn.jpg' %}" alt="CBRN">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">CBR System</h3>
            </div>
        </a>
      </div>    
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
        <a href="{% url 'gce:ffs' %}">
          <div class="card item-card card-block">
            <img src="{% static 'img/ffs.jpg' %}" alt="Fire Fighting">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Fire Fighting</h3>
            </div>
        </a>
      </div>        
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem; margin-top:1rem;">
        <a href="{% static 'FILES/GCE/WPI_of_Tk_T-72.pdf' %}#page=112" target="_blank">
          <div class="card item-card card-block">
            <img src="{% static 'img/wpi.png' %}" alt="WPI">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">WPI</h3>
            </div>
        </a>
      </div>        
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem; margin-top:1rem;">
        <a href="{% static 'FILES/GCE/GCE_Preci.pdf' %}" target="_blank">
          <div class="card item-card card-block">
            <img src="{% static 'img/precis.png' %}" alt="Precis">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Precis</h3>
            </div>
        </a>
      </div>                
    </div>
</div>
{% endblock content %}

gce/templates/gce/gcs.html
{% extends 'rebase.html' %}
{% load static %}

{% block style %}
<style>
    img{
height:150px;
width:100%;
}

.item{
padding-left:5px;
padding-right:5px;
}
.item-card{
transition:0.5s;
cursor:pointer;
}
.item-card-title{  
font-size:15px;
transition:1s;
cursor:pointer;
}
.item-card-title i{  
font-size:15px;
transition:1s;
cursor:pointer;
color:#ffa710
}
.card-title i:hover{
transform: scale(1.25) rotate(100deg); 
color:#18d4ca;

}
.card:hover{
transform: scale(1.05);
box-shadow: 10px 10px 15px rgba(0,0,0,0.3);
}
.card-text{
height:80px;  
}

.card::before, .card::after {
position: absolute;
top: 0;
right: 0;
bottom: 0;
left: 0;
transform: scale3d(0, 0, 1);
transition: transform .3s ease-out 0s;
background: rgba(255, 255, 255, 0.1);
content: '';
pointer-events: none;
}
.card::before {
transform-origin: left top;
}
.card::after {
transform-origin: right bottom;
}
.card:hover::before, .card:hover::after, .card:focus::before, .card:focus::after {
transform: scale3d(1, 1, 1);
}
</style>
{% endblock style %}

{% block title %}
    <title>
        Gun Control System
    </title>
{% endblock title %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'users:home' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'gce:home' %}">GCE</a></li>
    <li class="breadcrumb-item">GCE</li>
  </ol>
</nav>
<div class="container center" style="margin-top: 2rem;">
    <div class="row">
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
        <a href="{% static 'FILES/GCE/Technical Manual T-72.pdf' %}#page=34" target="_blank">
          <div class="card item-card card-block">
            <img src="{% static 'img/manual.png' %}" alt="Technical Manual">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Technical Manual</h3>
            </div>
        </a>
      </div>   
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
        <a href="{% static 'FILES/GCE/GCE_Preci.pdf' %}" target="_blank">
          <div class="card item-card card-block">
            <img src="{% static 'img/precis.png' %}" alt="Preci">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Preci</h3>
            </div>
        </a>
      </div>        
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
        <a href="{% static 'FILES/GCE/SCHEMATIC/GCE_SYSTEM.pdf' %}" target="_blank">
          <div class="card item-card card-block">
            <img src="{% static 'img/circuit.png' %}" alt="Circuit/Schematic Diag">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Circuit/Schematic Diag</h3>
            </div>
        </a>
      </div>    
      <div class="col-md-3 col-sm-6 item" style="padding-right: 1rem;">
        <a href="{% url 'gce:gcs_videos' %}">
          <div class="card item-card card-block">
            <img src="{% static 'img/vid.png' %}" alt="Videos">
              <h3 class="d-flex justify-content-center item-card-title mt-3 mb-3">Videos</h3>
            </div>
        </a>
      </div>         
    </div>
</div>
{% endblock content %}