gce/urls.py
from django.urls import path
from .views import (HomeView,
ALGSysView, GCSSysView, FFSSysView, CBRNView,
ALGVideoView,CBRNVideoView,GCSVideoView,FFSVideoView)


app_name = 'gce'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('alg/', ALGSysView.as_view(), name='alg'),
    path('gcs/', GCSSysView.as_view(), name='gcs'),
    path('ffs/', FFSSysView.as_view(), name='ffs'),
    path('cbrn/', CBRNView.as_view(), name='cbrn'),

    path('alg/video/', ALGVideoView.as_view(), name='alg_videos'),
    path('cbr/video/', CBRNVideoView.as_view(), name='cbr_videos'),
    path('gcs/video/', GCSVideoView.as_view(), name='gcs_videos'),
    path('ffs/video/', FFSVideoView.as_view(), name='ffs_videos'),

]

ietm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from users.views import (LoginView, LogoutView, LandingView, 
                        AboutView, RsvView, EsvView, RsvFlowView, 
                        EsvFlowView, RsvTransmitterView, RsvGalleryView, RsvSdpView, RsvIffView, RsvCiuView, RsvDisplaysystemView)
from search.views import SearchView

admin.site.site_header = "IETM Admin"
admin.site.site_title = "IETM Admin Portal"
admin.site.index_title = "Welcome to IETM Admin Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingView.as_view(), name='landing'),
    path('rsv/', RsvView.as_view(), name='rsv'),
    path('rsv/transmitter', RsvTransmitterView.as_view(), name='rsv-transmitter'),
    path('rsv/gallery', RsvGalleryView.as_view(), name='rsv-gallery'),
    path('rsv/rsv-flow-diagram/', RsvFlowView.as_view(), name='rsv-flow-diagram'),
    path('rsv/sdp', RsvSdpView.as_view(), name='rsv-sdp'),
    path('rsv/iff', RsvIffView.as_view(), name='rsv-iff'),
    path('rsv/ciu', RsvCiuView.as_view(), name='rsv-ciu'),
    path('rsv/displaysystem', RsvDisplaysystemView.as_view(), name='rsv-displaysystem'),
    path('esv/', EsvView.as_view(), name='esv'),
    path('esv-flow-diagram/', EsvFlowView.as_view(), name='esv-flow-diagram'),
    path('about/', AboutView.as_view(), name='about'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('auto/', include('auto.urls', namespace="auto")),
    path('elec/', include('elec.urls', namespace="elec")),
    path('gce/', include('gce.urls', namespace="gce")),
    path('ietm/', include('users.urls', namespace="users")),
    # api urls
    path('api/', include('users.api.urls', namespace="api")),
    path('search/', SearchView.as_view(), name='search'),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import (HomeView,
AutoSchemView,GceSchemView,ElecSchemView,SchematicsView,
TechnicalLiteratureView,PrecisView,
EMERsView,SMTView,
CBTPPTView,CBTGCEView,CBTGCEiView,CBTAutoView,CBTMainView,PPTMainView,
PPTGCEView,PPTElecView,PPTAutoView,GCELessonsView,
DefectView,
MiscView,MiscFilesView, MiscVideosView,
SearchListView)


app_name = 'users'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    path('schematics/', SchematicsView.as_view(), name='schem'),
    path('schematics/auto/', AutoSchemView.as_view(), name='sc_auto'),
    path('schematics/gce/', GceSchemView.as_view(), name='sc_gce'),
    path('schematics/elec/', ElecSchemView.as_view(), name='sc_elec'),

    path('tech_lit/', TechnicalLiteratureView.as_view(), name='technical_literature'),
    path('tech_lit/precis/', PrecisView.as_view(), name='precis'),
    
    path('emers/', EMERsView.as_view(), name='emer'),
    path('emers/smt/', SMTView.as_view(), name='smt'),

    path('cbt/', CBTPPTView.as_view(), name='cbt'),
    path('cbts/all', CBTMainView.as_view(), name='cbt_main'),
    path('ppts/all', PPTMainView.as_view(), name='ppt_main'),
    path('cbt/gce/', CBTGCEView.as_view(), name='cbt_gce'),
    path('cbt/gce-electronics/', CBTGCEiView.as_view(), name='cbt_gce_elec'),
    path('cbt/auto/', CBTAutoView.as_view(), name='cbt_auto'),
    path('ppt/auto/', PPTAutoView.as_view(), name='ppt_auto'),
    path('ppt/elec/', PPTElecView.as_view(), name='ppt_elec'),
    path('ppt/gce/', PPTGCEView.as_view(), name='ppt_gce'),
    path('ppt/gce/lessons/', GCELessonsView.as_view(), name='ppt_gce_lessons'),

    path('defects/', DefectView.as_view(), name='defect_report'),

    path('misc/', MiscView.as_view(), name='misc'),
    path('misc/files', MiscFilesView.as_view(), name='misc_files'),
    path('misc/videos', MiscVideosView.as_view(), name='misc_videos'),

    path('results/', SearchListView.as_view(), name='results')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{% block title %} IETM:3DTCR {% endblock title %}</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <!--<link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">-->

    <!-- Template Main CSS File -->
    <link href="{% static 'css/style-new.css' %}" rel="stylesheet">

    {% block style %}{% endblock style %}

</head>

<body>

  <body>
    {% block body %}
    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top d-flex align-items-center flex-column">
      <div class="w-100 header-box">
        <div
          class="d-flex align-items-center justify-content-between container"
        >
          <div class="logo">
            <a href="{% url 'landing' %}"
              ><img src="{% static 'img/Picture1.png' %}" alt="" class="img-fluid"
            /></a>
          </div>
          <div class="logo">
            <h1 class="text-light">
              <a href="{% url 'landing' %}"> <span>IETM : 3D TCR</span></a>
            </h1>
          </div>
          <div class="logo">
            <a href="{% url 'landing' %}"
              ><img src="{% static 'img/Picture2.png' %}" alt="" class="img-fluid"
            /></a>
          </div>
        </div>
      </div>
      <div class="bg-dark w-100 nav-items">
        <div class="d-flex align-items-center justify-content-between container">
          <nav id="navbar" class="navbar w-100">
            {% if user.is_authenticated %}
            <ul class="w-100 justify-content-between">
            <li>
              <a class="nav-link scrollto {% if request.path == '/ietm/'  %} active {% endif %}" href="{% url 'landing' %}">Home</a>
            </li>
            <li>
              <a class="nav-link scrollto {% if request.path == '/about/'  %} active {% endif %}" href="{% url 'about' %}">About</a>
            </li>
            <li>
              <a class="nav-link scrollto {% if request.path == '/ietm/tech_lit/'  %} active {% endif %}" href="{% url 'users:technical_literature' %}">Technical Literatures</a>
            </li>
            <li>
              <a class="nav-link scrollto {% if request.path == '/ietm/cbt/'  %} active {% endif %}" href="{% url 'users:cbt' %}">CBTs/PPTs</a>
            </li>
            <li>
              <a class="nav-link scrollto {% if request.path == '/ietm/defects/'  %} active {% endif %}" href="{% url 'users:defect_report' %}">Fault Compendium</a>
            </li>
            <li>
              <a class="nav-link scrollto {% if request.path == '/ietm/misc/'  %} active {% endif %}" href="{% url 'users:misc' %}">Misc</a>
            </li>
            <li>
              <a class="nav-link scrollto {% if request.path == '/search/'  %} active {% endif %}" href="{% url 'search' %}">Search</a>
            </li>
            <li>
              <a class="nav-link scrollto" href="/logout">Logout</a>
            </li>
          </ul>
          {% else %}
          <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
              <li class="nav-item active nav-link">
                Login to Browse Content <span class="sr-only">(current)</span>
              </li>
            </ul>
          </div>
          {% endif %}
            <i class="bi bi-list mobile-nav-toggle"></i>
          </nav>
          <!-- .navbar -->
        </div>
      </div>
      {% block breadcrumb %}{% endblock breadcrumb %}
    </header>
              <!-- ! Menu 2
              <li class="nav-item">
                <a href="{% url 'users:schem' %}" class="nav-link">Schematic Diagrams</a>
              </li>
               ! Menu 3 
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:emer' %}">EMERs</a>
              </li>
              ! Menu 4 -->
    
    <main>
    {% block content %}
      
    {% endblock content %}
   </main>  
       
    
 <!--<a href="#" class="back-to-top d-flex align-items-center justify-content-center">
  <i class="bi bi-arrow-up-short"></i></a>-->

{% endblock body %}
<!-- Vendor JS Files -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
{% block extra_js %}
<!--<script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'vendor/php-email-form/validate.js' %}"></script>
<script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>-->
{% endblock extra_js %}
<!-- Template Main JS File -->
<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/rebase.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="has-navbar-fixed-top has-background-grey-dark">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon/favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    {% block title %}
    
    {% endblock title %}

    {% block style %}
    {% endblock style %}

</head>

<body onload="init()" >

    <div>
      <nav class="navbar-expand-lg navbar navbar-dark bg-dark" style="margin-top: 1em;">
          {% if user.is_authenticated %}
          <a class="navbar-brand" href="{% url 'landing' %}">Home</a>
        
          <div class="collapse navbar-collapse" >
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
              <!-- ! Menu 1 -->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:technical_literature' %}">Technical Literatures</a>
              </li>
              <!-- ! Menu 2 -->
              <li class="nav-item">
                <a href="{% url 'users:schem' %}" class="nav-link">Schematic Diagrams</a>
              </li>
              <!-- ! Menu 3 -->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:emer' %}">EMERs</a>
              </li>
              <!-- ! Menu 4 -->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:cbt' %}">CBTs/PPTs</a>
              </li>
              <!-- ! Menu 5 -->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:defect_report' %}">Defect Reports</a>
              </li>
              <!-- ! Menu 6 -->            
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:misc' %}">Misc</a>
              </li>
              <!-- ! Menu 7 -->
              <li class="nav-item" style="margin-left: 2rem;">
                <a class="nav-link" href="/logout">Logout</a>
              </li>
            </ul>
              <a data-toggle="modal" data-target="#exampleModalCenter">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
              </a>
          </div>
          {% else %}
          <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
              <li class="nav-item active nav-link">
                Login to Browse Content <span class="sr-only">(current)</span>
              </li>
            </ul>
          </div>
          {% endif %}
      </nav>
    </div>
    <div id="app">
      <form target="_blank" action="{% url 'users:results' %}" method="get">
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Enter you search terms here</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                  <input type="text" placeholder="Enter Keyword here"
                          name="q"
                          autocomplete="off"
                          class="input"
                          style="width: 100%;"
                          v-model="query" @input="filterQS" @focus="drop=true" 
                          @keyup.esc="drop=false">
                  <div v-if="filteredqs && drop">
                    <ul>
                      <li v-for="query in filteredqs.slice(0,4)" @click="setQuery(query)"
                      style="background-color: #f5f5f5;
                      font-weight: 400; cursor: pointer;">[{query}]</li>
                    </ul>
                  </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Search</button>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
    {% block content %}
      
    {% endblock content %}
<script src="{% static 'js/vue.js' %}"></script>
<script src="{% static 'js/axios.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/jquery-3.5.1.slim.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script>
var myObject = new Vue({
    el: '#app',
    delimiters: ['[{','}]'],
    data: {
      query:'',
      files: [],
      videos: [],
      queryset:[],
      filteredqs:[],
      drop: false,
    },
    methods: {
      filterQS(){
        this.filteredqs = this.queryset.filter(query => {
          return query.toLowerCase().includes(this.query.toLowerCase())
        });
      },
      setQuery(query){
        this.query = query
        this.drop = false
      },
      getFiles(){
        axios
        .get('http://127.0.0.1:8000/api/files/?format=json')
        .then(response => (response['data'].forEach(element => {
             this.files.push(element['name'])
             this.queryset.push(element['name'])
        })))
      },
      getVideos(){
        axios
        .get('http://127.0.0.1:8000/api/videos/?format=json')
        .then(response => (response['data'].forEach(element => {
             this.videos.push(element['name'])
             this.queryset.push(element['name'])
        })))
      },
    },
    mounted () {
      this.getFiles();
      this.getVideos();
    },
})
</script>
</body>

</html>